### PR TITLE
prettier format-on-save in vscode

### PR DESCRIPTION
**Pull request by cspotcode**
Related to #15

### CODE REVIEW

**Comment by keithlayne** [comment]
You just wanna use defaults?  I'm fine with that generally, the only one that can be more annoying is the print width of 80 (IIRC).  This is super-trivial, I just hate to change the settings ever because it creates needless churn, although nothing really matters at this point.

Arrrrgh, all my annoying habits are on display.

**Comment by keithlayne** [comment]
And feel free to run `prettier --write` in this branch too if you wanna.  But if you need to take a break till the weekend, I can handle the light work :)

**Comment by cspotcode** [comment]
I agree about overriding the print width.  Pretty sure I did the same in
ts-node although I don't remember offhand.

**Comment by keithlayne** [comment]
This is what's in ts-node: https://github.com/TypeStrong/ts-node/blob/main/package.json#L172-L174

just single quotes AFAICT.  I'm ambivalent about putting stuff in package.json vs a config file.

This is what I have in one project:

```json
{
  "printWidth": 100,
  "proseWrap": "always",
  "singleQuote": true,
  "trailingComma": "all"
}
```

...although I have no clue what `proseWrap` does. I think somewhere 100-120 is probably okay. 🤷

**Comment by cspotcode** [comment]
> This is what I have in one project:

Works for me, feel free to add that config to this branch and merge it.

**Comment by keithlayne** [comment]
couple of random things:

1. I usually rebase, but didn't here because it was your branch. Probably silly, you know how to git.
2. Looks like you were using a tab width of 4, and prettier defaults to 2. I used the default but if that bugs you we can fix.

**Comment by cspotcode** [comment]
Ok sounds good.  I'm using vscode configured with prettier auto-formatting, so I'll do whatever it tells me.

With rebasing, is the goal to avoid merge commits?  Do you use github's "rebase and squash" merge option?

**Comment by keithlayne** [comment]
I meant avoiding "merge main into xxx" stuff.  I'm fine with merge commits, I use them exclusively for work stuff, for no terrific reason.  If I have conflicts with main on a branch I rebase the branch. I'm really not into squashing but it could make sense for a more mature project where you get more bite-sized PRs.  

Basically, I prefer if there are merge commits that they are all _into_ main, not the other way around. I have no issues rebasing, and I'll occasionally do interactive rebases to reorder commits or whatever.

I'm too tired, I'm rambling. I have feelings on these topics but I don't care that much.  :P

**Comment by cspotcode** [comment]
I'll do whatever.  I'm also not a fan of squash-merges.

**Pull request merged**
